<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: text_tools.proto

namespace App\TextTools;

use UnexpectedValueException;

/**
 * Protobuf type <code>text_tools.Transformer</code>
 */
class Transformer
{
    /**
     * Generated from protobuf enum <code>TRANSFORMER_UNSPECIFIED = 0;</code>
     */
    const TRANSFORMER_UNSPECIFIED = 0;
    /**
     * Generated from protobuf enum <code>TRANSFORMER_UPPERCASE = 1;</code>
     */
    const TRANSFORMER_UPPERCASE = 1;
    /**
     * Generated from protobuf enum <code>TRANSFORMER_LOWERCASE = 2;</code>
     */
    const TRANSFORMER_LOWERCASE = 2;

    private static $valueToName = [
        self::TRANSFORMER_UNSPECIFIED => 'TRANSFORMER_UNSPECIFIED',
        self::TRANSFORMER_UPPERCASE => 'TRANSFORMER_UPPERCASE',
        self::TRANSFORMER_LOWERCASE => 'TRANSFORMER_LOWERCASE',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

