<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: text_tools.proto

namespace App\TextTools;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>text_tools.TransformTextRequest</code>
 */
class TransformTextRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.text_tools.Transformer transformer = 1 [json_name = "transformer"];</code>
     */
    protected $transformer = 0;
    /**
     * Generated from protobuf field <code>string text = 2 [json_name = "text"];</code>
     */
    protected $text = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $transformer
     *     @type string $text
     * }
     */
    public function __construct($data = NULL) {
        \App\GPBMetadata\TextTools::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.text_tools.Transformer transformer = 1 [json_name = "transformer"];</code>
     * @return int
     */
    public function getTransformer()
    {
        return $this->transformer;
    }

    /**
     * Generated from protobuf field <code>.text_tools.Transformer transformer = 1 [json_name = "transformer"];</code>
     * @param int $var
     * @return $this
     */
    public function setTransformer($var)
    {
        GPBUtil::checkEnum($var, \App\TextTools\Transformer::class);
        $this->transformer = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string text = 2 [json_name = "text"];</code>
     * @return string
     */
    public function getText()
    {
        return $this->text;
    }

    /**
     * Generated from protobuf field <code>string text = 2 [json_name = "text"];</code>
     * @param string $var
     * @return $this
     */
    public function setText($var)
    {
        GPBUtil::checkString($var, True);
        $this->text = $var;

        return $this;
    }

}

