<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: textTools.proto

namespace App\TextTools;

use UnexpectedValueException;

/**
 * Protobuf type <code>textTools.Transformer</code>
 */
class Transformer
{
    /**
     * Generated from protobuf enum <code>UPPERCASE = 0;</code>
     */
    const UPPERCASE = 0;
    /**
     * Generated from protobuf enum <code>LOWERCASE = 1;</code>
     */
    const LOWERCASE = 1;

    private static $valueToName = [
        self::UPPERCASE => 'UPPERCASE',
        self::LOWERCASE => 'LOWERCASE',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

