version: '3'

services:
  browser-app:
    container_name: browser-app
    build:
      context: ./frontend
    stdin_open: true
    tty: true
    ports:
      - "1337:80"
    networks:
      - grpc-demo
  server:
    container_name: server
    build:
      context: ./server
    ports:
      - "50051:50051"
    networks:
      - grpc-demo
  envoy:
    container_name: envoy
    build:
      context: ./envoy
    ports:
      - "9999:9999"
    networks:
      - grpc-demo
  gateway:
    container_name: gateway
    build:
      context: ./gateway
    ports:
      - "8888:8888"
      - "8082:8082"
    networks:
      - grpc-demo
  swagger-ui:
    image: swaggerapi/swagger-ui
    container_name: "swagger-ui"
    ports:
      - "8083:8080"
    environment:
      API_URL: http://localhost:8888/text_tools.swagger.json
    networks:
      - grpc-demo
networks:
  grpc-demo:
    driver: bridge
