// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.19.3
// source: textTools.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Transformer int32

const (
	Transformer_UPPERCASE Transformer = 0
	Transformer_LOWERCASE Transformer = 1
)

// Enum value maps for Transformer.
var (
	Transformer_name = map[int32]string{
		0: "UPPERCASE",
		1: "LOWERCASE",
	}
	Transformer_value = map[string]int32{
		"UPPERCASE": 0,
		"LOWERCASE": 1,
	}
)

func (x Transformer) Enum() *Transformer {
	p := new(Transformer)
	*p = x
	return p
}

func (x Transformer) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Transformer) Descriptor() protoreflect.EnumDescriptor {
	return file_textTools_proto_enumTypes[0].Descriptor()
}

func (Transformer) Type() protoreflect.EnumType {
	return &file_textTools_proto_enumTypes[0]
}

func (x Transformer) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Transformer.Descriptor instead.
func (Transformer) EnumDescriptor() ([]byte, []int) {
	return file_textTools_proto_rawDescGZIP(), []int{0}
}

type Transformation struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Transformer Transformer `protobuf:"varint,1,opt,name=transformer,proto3,enum=textTools.Transformer" json:"transformer,omitempty"`
	Text        string      `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
}

func (x *Transformation) Reset() {
	*x = Transformation{}
	if protoimpl.UnsafeEnabled {
		mi := &file_textTools_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Transformation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Transformation) ProtoMessage() {}

func (x *Transformation) ProtoReflect() protoreflect.Message {
	mi := &file_textTools_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Transformation.ProtoReflect.Descriptor instead.
func (*Transformation) Descriptor() ([]byte, []int) {
	return file_textTools_proto_rawDescGZIP(), []int{0}
}

func (x *Transformation) GetTransformer() Transformer {
	if x != nil {
		return x.Transformer
	}
	return Transformer_UPPERCASE
}

func (x *Transformation) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type TransformationResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result string `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
}

func (x *TransformationResult) Reset() {
	*x = TransformationResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_textTools_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TransformationResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransformationResult) ProtoMessage() {}

func (x *TransformationResult) ProtoReflect() protoreflect.Message {
	mi := &file_textTools_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransformationResult.ProtoReflect.Descriptor instead.
func (*TransformationResult) Descriptor() ([]byte, []int) {
	return file_textTools_proto_rawDescGZIP(), []int{1}
}

func (x *TransformationResult) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

var File_textTools_proto protoreflect.FileDescriptor

var file_textTools_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x74, 0x65, 0x78, 0x74, 0x54, 0x6f, 0x6f, 0x6c, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x09, 0x74, 0x65, 0x78, 0x74, 0x54, 0x6f, 0x6f, 0x6c, 0x73, 0x22, 0x5e, 0x0a, 0x0e,
	0x54, 0x72, 0x61, 0x6e, 0x73, 0x66, 0x6f, 0x72, 0x6d, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x38,
	0x0a, 0x0b, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x66, 0x6f, 0x72, 0x6d, 0x65, 0x72, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0e, 0x32, 0x16, 0x2e, 0x74, 0x65, 0x78, 0x74, 0x54, 0x6f, 0x6f, 0x6c, 0x73, 0x2e,
	0x54, 0x72, 0x61, 0x6e, 0x73, 0x66, 0x6f, 0x72, 0x6d, 0x65, 0x72, 0x52, 0x0b, 0x74, 0x72, 0x61,
	0x6e, 0x73, 0x66, 0x6f, 0x72, 0x6d, 0x65, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x65, 0x78, 0x74,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x65, 0x78, 0x74, 0x22, 0x2e, 0x0a, 0x14,
	0x54, 0x72, 0x61, 0x6e, 0x73, 0x66, 0x6f, 0x72, 0x6d, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65,
	0x73, 0x75, 0x6c, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x2a, 0x2b, 0x0a, 0x0b,
	0x54, 0x72, 0x61, 0x6e, 0x73, 0x66, 0x6f, 0x72, 0x6d, 0x65, 0x72, 0x12, 0x0d, 0x0a, 0x09, 0x55,
	0x50, 0x50, 0x45, 0x52, 0x43, 0x41, 0x53, 0x45, 0x10, 0x00, 0x12, 0x0d, 0x0a, 0x09, 0x4c, 0x4f,
	0x57, 0x45, 0x52, 0x43, 0x41, 0x53, 0x45, 0x10, 0x01, 0x32, 0xb5, 0x01, 0x0a, 0x09, 0x54, 0x65,
	0x78, 0x74, 0x54, 0x6f, 0x6f, 0x6c, 0x73, 0x12, 0x4d, 0x0a, 0x0d, 0x54, 0x72, 0x61, 0x6e, 0x73,
	0x66, 0x6f, 0x72, 0x6d, 0x54, 0x65, 0x78, 0x74, 0x12, 0x19, 0x2e, 0x74, 0x65, 0x78, 0x74, 0x54,
	0x6f, 0x6f, 0x6c, 0x73, 0x2e, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x66, 0x6f, 0x72, 0x6d, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x1a, 0x1f, 0x2e, 0x74, 0x65, 0x78, 0x74, 0x54, 0x6f, 0x6f, 0x6c, 0x73, 0x2e,
	0x54, 0x72, 0x61, 0x6e, 0x73, 0x66, 0x6f, 0x72, 0x6d, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65,
	0x73, 0x75, 0x6c, 0x74, 0x22, 0x00, 0x12, 0x59, 0x0a, 0x15, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x66,
	0x6f, 0x72, 0x6d, 0x41, 0x6e, 0x64, 0x53, 0x70, 0x6c, 0x69, 0x74, 0x54, 0x65, 0x78, 0x74, 0x12,
	0x19, 0x2e, 0x74, 0x65, 0x78, 0x74, 0x54, 0x6f, 0x6f, 0x6c, 0x73, 0x2e, 0x54, 0x72, 0x61, 0x6e,
	0x73, 0x66, 0x6f, 0x72, 0x6d, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x1a, 0x1f, 0x2e, 0x74, 0x65, 0x78,
	0x74, 0x54, 0x6f, 0x6f, 0x6c, 0x73, 0x2e, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x66, 0x6f, 0x72, 0x6d,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x22, 0x00, 0x28, 0x01, 0x30,
	0x01, 0x42, 0x24, 0x5a, 0x22, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f,
	0x65, 0x6b, 0x6b, 0x69, 0x6e, 0x6f, 0x78, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x2d, 0x64, 0x65, 0x6d,
	0x6f, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_textTools_proto_rawDescOnce sync.Once
	file_textTools_proto_rawDescData = file_textTools_proto_rawDesc
)

func file_textTools_proto_rawDescGZIP() []byte {
	file_textTools_proto_rawDescOnce.Do(func() {
		file_textTools_proto_rawDescData = protoimpl.X.CompressGZIP(file_textTools_proto_rawDescData)
	})
	return file_textTools_proto_rawDescData
}

var file_textTools_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_textTools_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_textTools_proto_goTypes = []interface{}{
	(Transformer)(0),             // 0: textTools.Transformer
	(*Transformation)(nil),       // 1: textTools.Transformation
	(*TransformationResult)(nil), // 2: textTools.TransformationResult
}
var file_textTools_proto_depIdxs = []int32{
	0, // 0: textTools.Transformation.transformer:type_name -> textTools.Transformer
	1, // 1: textTools.TextTools.TransformText:input_type -> textTools.Transformation
	1, // 2: textTools.TextTools.TransformAndSplitText:input_type -> textTools.Transformation
	2, // 3: textTools.TextTools.TransformText:output_type -> textTools.TransformationResult
	2, // 4: textTools.TextTools.TransformAndSplitText:output_type -> textTools.TransformationResult
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_textTools_proto_init() }
func file_textTools_proto_init() {
	if File_textTools_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_textTools_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Transformation); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_textTools_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TransformationResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_textTools_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_textTools_proto_goTypes,
		DependencyIndexes: file_textTools_proto_depIdxs,
		EnumInfos:         file_textTools_proto_enumTypes,
		MessageInfos:      file_textTools_proto_msgTypes,
	}.Build()
	File_textTools_proto = out.File
	file_textTools_proto_rawDesc = nil
	file_textTools_proto_goTypes = nil
	file_textTools_proto_depIdxs = nil
}
